// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logs} from '../models';
import {tools} from '../models';
import {main} from '../models';

export function GetExtractedToolsDirectory():Promise<string>;

export function GetLogs():Promise<Array<logs.Entry>>;

export function GetToolDetails(arg1:string):Promise<tools.ToolPackage>;

export function GetToolsDirectory():Promise<string>;

export function InstallStoreTool(arg1:string):Promise<tools.ToolValidationResult>;

export function InstallTool(arg1:string):Promise<tools.ToolValidationResult>;

export function ListToolStore():Promise<Array<main.ToolStorePackage>>;

export function ListTools():Promise<Array<tools.ToolPackage>>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenTool(arg1:string):Promise<tools.ToolPackage>;

export function PreviewToolPackage(arg1:string):Promise<tools.ToolPackage>;

export function ReadToolModule(arg1:string,arg2:string):Promise<string>;

export function RefreshTools():Promise<Array<tools.ToolPackage>>;

export function RemoveTool(arg1:string):Promise<void>;

export function RunToolAction(arg1:string,arg2:string):Promise<logs.Entry>;

export function RuntimeCryptoHashFile(arg1:string,arg2:string):Promise<string>;

export function RuntimeDialogsOpenFile(arg1:main.RuntimeOpenFileDialogOptions):Promise<string>;

export function RuntimeDialogsSaveFile(arg1:main.RuntimeSaveFileDialogOptions):Promise<string>;

export function RuntimeEnvGet(arg1:string):Promise<string>;

export function RuntimeFilesystemExists(arg1:string):Promise<boolean>;

export function RuntimeFilesystemListDir(arg1:string):Promise<Array<main.RuntimeDirectoryEntry>>;

export function RuntimeFilesystemMkdirAll(arg1:string):Promise<void>;

export function RuntimeFilesystemReadFile(arg1:string):Promise<string>;

export function RuntimeFilesystemReadFileBase64(arg1:string):Promise<string>;

export function RuntimeFilesystemRemoveDir(arg1:string):Promise<void>;

export function RuntimeFilesystemRemoveFile(arg1:string):Promise<void>;

export function RuntimeFilesystemStat(arg1:string):Promise<main.RuntimeFileInfo>;

export function RuntimeFilesystemWriteFile(arg1:string,arg2:string):Promise<void>;

export function RuntimeLogsWrite(arg1:string,arg2:string):Promise<logs.Entry>;

export function RuntimeOSInfo():Promise<main.RuntimeOSInfo>;

export function RuntimeOSIsAdmin():Promise<boolean>;

export function RuntimeOSPlatform():Promise<string>;

export function RuntimePathBaseName(arg1:string):Promise<string>;

export function RuntimePathDirName(arg1:string):Promise<string>;

export function RuntimePathExtName(arg1:string):Promise<string>;

export function RuntimePathFromSlash(arg1:string):Promise<string>;

export function RuntimePathIsAbs(arg1:string):Promise<boolean>;

export function RuntimePathJoin(arg1:Array<string>):Promise<string>;

export function RuntimePathNormalize(arg1:string):Promise<string>;

export function RuntimePathToSlash(arg1:string):Promise<string>;

export function RuntimePowerShellExec(arg1:string,arg2:main.RuntimeExecOptions):Promise<main.RuntimeExecResult>;

export function RuntimeProcessExec(arg1:string,arg2:Array<string>,arg3:main.RuntimeExecOptions):Promise<main.RuntimeExecResult>;

export function RuntimeProcessWhich(arg1:string):Promise<string>;

export function RuntimeShellExec(arg1:string,arg2:main.RuntimeExecOptions):Promise<main.RuntimeExecResult>;

export function RuntimeStorageEnsure(arg1:string):Promise<main.RuntimeStoragePaths>;

export function RuntimeStoragePaths(arg1:string):Promise<main.RuntimeStoragePaths>;

export function SelectToolPackage():Promise<string>;

export function UpdateStoreTool(arg1:string):Promise<tools.ToolValidationResult>;

export function UpdateTool(arg1:string):Promise<tools.ToolValidationResult>;

export function ValidateTool(arg1:string):Promise<tools.ToolValidationResult>;
