// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetExtractedToolsDirectory() {
  return window['go']['main']['App']['GetExtractedToolsDirectory']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetToolDetails(arg1) {
  return window['go']['main']['App']['GetToolDetails'](arg1);
}

export function GetToolsDirectory() {
  return window['go']['main']['App']['GetToolsDirectory']();
}

export function InstallStoreTool(arg1) {
  return window['go']['main']['App']['InstallStoreTool'](arg1);
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function ListToolStore() {
  return window['go']['main']['App']['ListToolStore']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenTool(arg1) {
  return window['go']['main']['App']['OpenTool'](arg1);
}

export function PreviewToolPackage(arg1) {
  return window['go']['main']['App']['PreviewToolPackage'](arg1);
}

export function ReadToolModule(arg1, arg2) {
  return window['go']['main']['App']['ReadToolModule'](arg1, arg2);
}

export function RefreshTools() {
  return window['go']['main']['App']['RefreshTools']();
}

export function RemoveTool(arg1) {
  return window['go']['main']['App']['RemoveTool'](arg1);
}

export function RunToolAction(arg1, arg2) {
  return window['go']['main']['App']['RunToolAction'](arg1, arg2);
}

export function RuntimeCryptoHashFile(arg1, arg2) {
  return window['go']['main']['App']['RuntimeCryptoHashFile'](arg1, arg2);
}

export function RuntimeDialogsOpenFile(arg1) {
  return window['go']['main']['App']['RuntimeDialogsOpenFile'](arg1);
}

export function RuntimeDialogsSaveFile(arg1) {
  return window['go']['main']['App']['RuntimeDialogsSaveFile'](arg1);
}

export function RuntimeEnvGet(arg1) {
  return window['go']['main']['App']['RuntimeEnvGet'](arg1);
}

export function RuntimeFilesystemExists(arg1) {
  return window['go']['main']['App']['RuntimeFilesystemExists'](arg1);
}

export function RuntimeFilesystemListDir(arg1) {
  return window['go']['main']['App']['RuntimeFilesystemListDir'](arg1);
}

export function RuntimeFilesystemMkdirAll(arg1) {
  return window['go']['main']['App']['RuntimeFilesystemMkdirAll'](arg1);
}

export function RuntimeFilesystemReadFile(arg1) {
  return window['go']['main']['App']['RuntimeFilesystemReadFile'](arg1);
}

export function RuntimeFilesystemReadFileBase64(arg1) {
  return window['go']['main']['App']['RuntimeFilesystemReadFileBase64'](arg1);
}

export function RuntimeFilesystemRemoveDir(arg1) {
  return window['go']['main']['App']['RuntimeFilesystemRemoveDir'](arg1);
}

export function RuntimeFilesystemRemoveFile(arg1) {
  return window['go']['main']['App']['RuntimeFilesystemRemoveFile'](arg1);
}

export function RuntimeFilesystemStat(arg1) {
  return window['go']['main']['App']['RuntimeFilesystemStat'](arg1);
}

export function RuntimeFilesystemWriteFile(arg1, arg2) {
  return window['go']['main']['App']['RuntimeFilesystemWriteFile'](arg1, arg2);
}

export function RuntimeLogsWrite(arg1, arg2) {
  return window['go']['main']['App']['RuntimeLogsWrite'](arg1, arg2);
}

export function RuntimeOSInfo() {
  return window['go']['main']['App']['RuntimeOSInfo']();
}

export function RuntimeOSIsAdmin() {
  return window['go']['main']['App']['RuntimeOSIsAdmin']();
}

export function RuntimeOSPlatform() {
  return window['go']['main']['App']['RuntimeOSPlatform']();
}

export function RuntimePathBaseName(arg1) {
  return window['go']['main']['App']['RuntimePathBaseName'](arg1);
}

export function RuntimePathDirName(arg1) {
  return window['go']['main']['App']['RuntimePathDirName'](arg1);
}

export function RuntimePathExtName(arg1) {
  return window['go']['main']['App']['RuntimePathExtName'](arg1);
}

export function RuntimePathFromSlash(arg1) {
  return window['go']['main']['App']['RuntimePathFromSlash'](arg1);
}

export function RuntimePathIsAbs(arg1) {
  return window['go']['main']['App']['RuntimePathIsAbs'](arg1);
}

export function RuntimePathJoin(arg1) {
  return window['go']['main']['App']['RuntimePathJoin'](arg1);
}

export function RuntimePathNormalize(arg1) {
  return window['go']['main']['App']['RuntimePathNormalize'](arg1);
}

export function RuntimePathToSlash(arg1) {
  return window['go']['main']['App']['RuntimePathToSlash'](arg1);
}

export function RuntimePowerShellExec(arg1, arg2) {
  return window['go']['main']['App']['RuntimePowerShellExec'](arg1, arg2);
}

export function RuntimeProcessExec(arg1, arg2, arg3) {
  return window['go']['main']['App']['RuntimeProcessExec'](arg1, arg2, arg3);
}

export function RuntimeProcessWhich(arg1) {
  return window['go']['main']['App']['RuntimeProcessWhich'](arg1);
}

export function RuntimeShellExec(arg1, arg2) {
  return window['go']['main']['App']['RuntimeShellExec'](arg1, arg2);
}

export function RuntimeStorageEnsure(arg1) {
  return window['go']['main']['App']['RuntimeStorageEnsure'](arg1);
}

export function RuntimeStoragePaths(arg1) {
  return window['go']['main']['App']['RuntimeStoragePaths'](arg1);
}

export function SelectToolPackage() {
  return window['go']['main']['App']['SelectToolPackage']();
}

export function UpdateStoreTool(arg1) {
  return window['go']['main']['App']['UpdateStoreTool'](arg1);
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}

export function ValidateTool(arg1) {
  return window['go']['main']['App']['ValidateTool'](arg1);
}
